#!/usr/bin/env ruby
# Patches the Podfile generated by `expo prebuild` to disable code signing
# on all pod targets. Required for building unsigned IPAs on Expo SDK 51+.
# See: https://github.com/expo/expo/issues/29526

podfile = File.read("Podfile")

# Locate the post_install block by finding "post_install do |installer|"
# and tracking do/end nesting to find the matching closing end.
lines = podfile.lines
start_idx = lines.index { |l| l.match?(/^\s*post_install\s+do\s*\|/) }

unless start_idx
  puts "ERROR: post_install block not found in Podfile"
  exit 1
end

# Track do/end nesting to find the matching closing end
depth = 0
end_idx = nil
lines[start_idx..].each_with_index do |line, offset|
  depth += line.scan(/\bdo\b/).size
  depth -= line.scan(/\bend\b/).size

  if depth == 0 && offset > 0
    end_idx = start_idx + offset
    break
  end
end

unless end_idx
  puts "ERROR: could not find matching end for post_install"
  exit 1
end

fix = <<~'FIX'

  # Disable code signing for unsigned IPA builds
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
FIX

lines.insert(end_idx, fix)
File.write("Podfile", lines.join)
puts "Podfile patched: inserted code signing fix at line #{end_idx + 1}"
