#!/usr/bin/env ruby
# Patches the Podfile generated by `expo prebuild` to disable code signing
# on all pod targets. Required for building unsigned IPAs on Expo SDK 51+.
# See: https://github.com/expo/expo/issues/29526

podfile = File.read("Podfile")
lines = podfile.lines

last_end = lines.rindex { |l| l.match?(/^end\s*$/) }
unless last_end
  puts "ERROR: Could not find closing 'end' in Podfile"
  exit 1
end

fix = [
  "  # Disable code signing for unsigned IPA builds (patch-podfile.rb)\n",
  "  installer.pods_project.targets.each do |target|\n",
  "    target.build_configurations.each do |config|\n",
  "      config.build_settings[\"EXPANDED_CODE_SIGN_IDENTITY\"] = \"\"\n",
  "      config.build_settings[\"CODE_SIGNING_REQUIRED\"] = \"NO\"\n",
  "      config.build_settings[\"CODE_SIGNING_ALLOWED\"] = \"NO\"\n",
  "    end\n",
  "  end\n",
  "\n",
]
lines.insert(last_end, *fix)
File.write("Podfile", lines.join)
puts "Podfile patched successfully (code signing disabled for #{lines.size} lines)"
